<?php
$title = 'Edit Member';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'blog_editMember',
     array(
         'action' => 'editMember',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('mail'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
