<?php


$title = 'My Profil';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'blog_editMember',
     array(
         'action' => 'editMember',
         'id'     => $this->id,
     )
 ));
 $form->prepare();
 
 
 echo $this->form()->openTag($form);

 echo $this->formHidden($form->get('id')); ?>
 <div class="form-control">
<?php
 echo $this->formRow($form->get('name'));
 ?>
 </div>
 <div class="form-control">
<?php 
 echo $this->formRow($form->get('mail'));
  ?>
 </div>
 <div class="form-control">
<?php 
 echo $this->formSubmit($form->get('submit'));
  ?>
 </div>
<?php 
 echo $this->form()->closeTag();
 ?>
 <?php echo $this->form()->openTag($form); ?>
