<?php

$title = 'Ajouter un nouveau Tutorial';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('tutorial_add', array('action' => 'add')));

 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('title')).'<br>';
 echo $this->formRow($form->get('contente')).'<br>';
 echo $this->formSubmit($form->get('submit')).'<br>';
 echo $this->form()->closeTag();
